import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { CheckCircle2, ShieldCheck } from "lucide-react"

const profiles = [
  { name: "ImagingStudy Profile", status: "Implemented" },
  { name: "DiagnosticReportImaging Profile", status: "Implemented" },
  { name: "ServiceRequest Profile", status: "Implemented" },
  { name: "ABDM Health Record Push", status: "Ready" },
]

export function ABDMCompliance() {
  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div>
        <h2 className="text-2xl font-bold">ABDM Compliance</h2>
        <p className="text-sm text-muted-foreground">
          Ayushman Bharat Digital Mission conformance status
        </p>
      </div>

      {/* FHIR Conformance */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-50 text-emerald-600">
              <ShieldCheck className="h-5 w-5" />
            </div>
            <div>
              <CardTitle className="text-lg">FHIR Conformance</CardTitle>
              <CardDescription>NRCeS ABDM IG v6.5.0</CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Profile / Capability</TableHead>
                <TableHead className="text-right">Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {profiles.map((p) => (
                <TableRow key={p.name}>
                  <TableCell className="font-medium">{p.name}</TableCell>
                  <TableCell className="text-right">
                    <div className="flex items-center justify-end gap-2">
                      <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                      <Badge variant="success">{p.status}</Badge>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Additional Details */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Implementation Details</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-sm">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-muted-foreground">FHIR Version</p>
              <p className="font-medium">R4 (4.0.1)</p>
            </div>
            <div>
              <p className="text-muted-foreground">Implementation Guide</p>
              <p className="font-medium">NRCeS ABDM IG v6.5.0</p>
            </div>
            <div>
              <p className="text-muted-foreground">Terminology Bindings</p>
              <p className="font-medium">SNOMED CT, ICD-10, LOINC</p>
            </div>
            <div>
              <p className="text-muted-foreground">Transport</p>
              <p className="font-medium">FHIR REST + ABDM Gateway</p>
            </div>
          </div>

          <div className="rounded-md bg-blue-50 border border-blue-200 p-4">
            <p className="text-sm text-blue-900">
              All imaging reports generated by this plugin conform to the NRCeS ABDM FHIR
              Implementation Guide v6.5.0 and can be pushed to the ABDM Health Locker. The
              plugin generates compliant <code className="bg-blue-100 px-1 rounded">ImagingStudy</code>,{" "}
              <code className="bg-blue-100 px-1 rounded">DiagnosticReport</code>, and{" "}
              <code className="bg-blue-100 px-1 rounded">ServiceRequest</code> resources for
              each radiology workflow event.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
